apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mr6mhrmww-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mr6mhrmww-nodejs 
  name: mr6mhrmww-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mr6mhrmww-nodejs 
